# Service account used by Prometheus for target discovery
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
# Local role for listing services/endpoints/pods in the current namespace
apiVersion: v1
kind: Role
metadata:
  name: prometheus-reader
rules:
- apiGroups: null
  attributeRestrictions: null
  resources:
  - pods
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: RoleBinding
metadata:
  name: prometheus-reader
roleRef:
  name: prometheus-reader
subjects:
- kind: ServiceAccount
  name: prometheus
