apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kube-state-metrics
  annotations:
    "openshift.io/display-name": Kubenertes state metrics
    description: |
      A service for collecting state metrics from Kubernetes clusteres.
    iconClass: icon-cogs
    tags: "monitoring,prometheus,time-series"
parameters:
- description: The namespace to instantiate kube-state-metrics under. Defaults to 'kube-system'.
  name: NAMESPACE
  value: kube-system
- description: The location of the proxy image
  name: IMAGE_PROXY
  value: openshift/oauth-proxy:v1.0.0
- description: The location of the kube-state-metrics image
  name: IMAGE_KUBE_STATE_METRICS
  value: gcr.io/google_containers/kube-state-metrics:v1.1.0
- description: The session secret for the proxy
  name: SESSION_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{43}"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: kube-state-metrics
    namespace: "${NAMESPACE}"

- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: kube-state-metrics
  rules:
  - apiGroups: [""]
    resources:
    - nodes
    - pods
    - services
    - resourcequotas
    - replicationcontrollers
    - limitranges
    - persistentvolumeclaims
    - namespaces
    verbs: ["list", "watch"]
  - apiGroups: ["extensions"]
    resources:
    - daemonsets
    - deployments
    - replicasets
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources:
    - statefulsets
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources:
    - cronjobs
    - jobs
    verbs: ["list", "watch"]

# Grant permissions to read cluster resources
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: kube-state-metrics
  roleRef:
    kind: ClusterRole
    name: kube-state-metrics
  subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: "${NAMESPACE}"

# Grant permissions to authenticate/authorize clients using tokens
- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: kube-state-metrics-auth
  roleRef:
    kind: ClusterRole
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: "${NAMESPACE}"

- apiVersion: v1
  kind: Service
  metadata:
    name: ksm-proxy
    namespace: "${NAMESPACE}"
    labels:
      app: kube-state-metrics
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/scheme: https
      service.alpha.openshift.io/serving-cert-secret-name: ksm-tls
  spec:
    ports:
    - name: ksm-proxy
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: kube-state-metrics

- apiVersion: v1
  kind: Secret
  metadata:
    name: ksm-secrets
    namespace: "${NAMESPACE}"
  stringData:
    session_secret: "${SESSION_SECRET}="

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: kube-state-metrics
    namespace: "${NAMESPACE}"
  spec:
    selector:
      matchLabels:
        app: kube-state-metrics
    replicas: 1
    template:
      metadata:
        labels:
          app: kube-state-metrics
      spec:
        serviceAccountName: kube-state-metrics
        containers:
        # Deploy kube-state-metrics behind an oauth proxy
        - name: ksm-proxy
          image: ${IMAGE_PROXY}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
          args:
          - -provider=openshift
          - -https-address=:8443
          - -http-address=
          - -email-domain=*
          - -upstream=http://localhost:8080
          - -client-id=system:serviceaccount:${NAMESPACE}:kube-state-metrics
          - -openshift-ca=/etc/pki/tls/cert.pem
          - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get", "resourceName": "${NAMESPACE}", "namespace": "${NAMESPACE}"}}'
          - -tls-cert=/etc/tls/private/tls.crt
          - -tls-key=/etc/tls/private/tls.key
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -cookie-secret-file=/etc/proxy/secrets/session_secret
          volumeMounts:
          - mountPath: /etc/tls/private
            name: ksm-tls
          - mountPath: /etc/proxy/secrets
            name: ksm-secrets
        - name: kube-state-metrics
          image: "${IMAGE_KUBE_STATE_METRICS}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
        volumes:
        - name: ksm-secrets
          secret:
            secretName: ksm-secrets
        - name: ksm-tls
          secret:
            secretName: ksm-tls
